# Generated by Django 2.2.6 on 2019-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
