# Generated by Django 2.2.6 on 2019-12-13 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_auto_20191213_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='friends', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
