# Generated by Django 2.2.6 on 2019-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_friends_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='img',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
