# Generated by Django 2.2.6 on 2019-12-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20191214_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='date',
        ),
        migrations.AlterField(
            model_name='userposts',
            name='img',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
