# Generated by Django 2.2.6 on 2019-12-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20191216_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='img',
        ),
        migrations.AddField(
            model_name='userposts',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/', verbose_name=''),
        ),
    ]
