# Generated by Django 2.2.6 on 2019-12-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20191217_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(default=0, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
