# Generated by Django 2.2.6 on 2019-12-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20191217_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='user',
        ),
    ]
