# Generated by Django 2.2.6 on 2019-12-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_userposts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('hobbies', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
