# Generated by Django 2.2.6 on 2019-12-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_myprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
