# Generated by Django 2.2.6 on 2019-12-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20191221_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchuser', models.CharField(max_length=100)),
            ],
        ),
    ]
