# Generated by Django 2.2.6 on 2020-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20200103_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='social.MyProfile'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
