# Generated by Django 2.2.6 on 2020-01-09 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_auto_20200105_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
